erDiagram
    DONO ||--o{ ANIMAL : possui
    
    DONO {
        int id PK
        varchar nome_completo
        varchar cpf
        varchar email
        varchar telefone
        varchar endereco
    }
    
    ANIMAL {
        int id PK
        int id_dono FK
        varchar nome_pet
        varchar especie
        varchar raca
        date data_nascimento
        text observacoes
    }
